language: r
r:
  - release

warnings_are_errors: false
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

r_packages:
  - covr
  - rgdal
  - rgeos

after_success:
  - Rscript -e "library(covr); coveralls()"

notifications:
  email:
    on_success: change
    on_failure: change
