library(svamap)
data(NUTS_20M)
pts <- read_point_data()
polys <- svamap::match_to_county(pts, NUTS_20M, "NUTS_ID")
path_to_data <- write_data(list(polys, pts))
svamap::write_page(path_to_data, path = "/tmp", overwrite = TRUE, browse = FALSE)
