library(svamap)
data(NUTS_20M)
pts <- read_point_data("/media/t/Falkenrapporter/E16-036 Grundrapport.csv")
pts$popup_text <- paste0(pts$Djurslag, "<br>Ankomstdatum: ", as.Date(pts$Ankomstdatum))
polys <- svamap::match_to_county(pts, NUTS_20M, "NUTS_ID")
pts@data <- data.frame(popup_text = pts@data$popup_text, stringsAsFactors = FALSE)
text <- ifelse(polys$count == 1, "negativt prov", "negativa prover")
polys@data$popup_text <- ifelse(is.na(polys@data$count), polys@data$name, paste0(polys@data$name, "<br>", polys@data$count, " ", text))
path_to_data <- svamap::write_data(list(polys, pts))
svamap::write_page(data = path_to_data, path = "/media/ESS_webpages/CWD2/", template = "map2", overwrite = TRUE, browse = FALSE)
